services:
  hamatetsu-scheduler-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "http://hamatetsu-scheduler-api:5063/api"
    container_name: hamatetsu-scheduler-web
    ports:
      - "3000:3000"
    restart: unless-stopped
